version: '3'

services:
  unfurl-bot:
    build: .
    ports:
      - "4567:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RACK_ENV=development
      - PORT=8080
