services:
  - name: trello
    match: trello\.com/c/
    handler: trello_handler
  - name: kaiten
    match: kaiten\.ru/.*?/card/
    handler: kaiten_handler
  - name: pachca
    match: pachca\.com/.*?/messages/
    handler: pachca_handler
  - name: pachca_app
    match: app\.pachca\.com/chats/.*?\?message=
    handler: pachca_handler
